repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6
    hooks:
      - id: clang-format
        types_or: [file]
        files: \.(cpp|hpp|ipp|cu|cuh)$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: trailing-whitespace
      exclude: \.(diff|patch)$
    - id: end-of-file-fixer
      exclude: \.(diff|patch)$
    - id: check-yaml
    - id: check-added-large-files

  - repo: local
    hooks:
    - id: license
      name: license
      language: system
      entry: ci/check_license.py
      files: \.(cpp|hpp|ipp|cu|cuh)$
